# Generated by Django 3.2.5 on 2022-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('married', 'married'), ('single', 'single')], default='1', max_length=20),
        ),
    ]
