# Generated by Django 3.2.5 on 2022-05-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plannedHours', models.IntegerField()),
                ('consumedHours', models.IntegerField()),
                ('remainingHours', models.IntegerField()),
                ('important_message', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('in progress', 'in progress'), ('completed', 'completed'), ('paused', 'paused'), ('not started', 'not started')], default='not started', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-important_message'],
            },
        ),
    ]
