# Generated by Django 3.2.5 on 2022-05-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='consumedHours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='plannedHours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='remainingHours',
            field=models.IntegerField(blank=True, default=8),
        ),
    ]
